chore: added merge task logic and tests
MapColonies/discrete-overseer-creator pull request #136
Opened 2022-05-16 14:30 UTC by CL-SHLOMIKONCHA

| Question                | Answer                                                                          |
| ---------------- | -------------------------------------------------------------------------- |
| Bug fix         | ✔/✖                                                                        |
| New feature     | ✔/✖                                                                        |
| Breaking change | ✔/✖                                                                        |
| Deprecations    | ✔/✖                                                                        |
| Documentation   | ✔/✖                                                                        |
| Tests added     | ✔/✖                                                                        |
| Chore            | ✔/✖                                                                       |

Related issues: #XXX , #XXX ...
Closes #XXX ...

Further  information:

2022-05-17 09:32 UTC, asafMasa requested changes

2022-05-17 09:32 UTC, asafMasa commented on tests/unit/layers/models/tasker.spec.ts
> +  describe('createIngestionTask', () => {
update remark to the actual ingestion / job task types

2022-05-17 09:32 UTC, asafMasa commented on src/serviceClients/jobManagerClient.ts
> +          type: jobType === JobType.UPDATE ? TaskType.MERGE : TaskType.DISCRETE_TILING,
type - should come from config

2022-05-17 09:32 UTC, asafMasa commented on src/serviceClients/jobManagerClient.ts
> +        type: TaskType.MERGE,
type - should come from config

2022-05-17 09:32 UTC, asafMasa commented on src/layers/models/tasker.ts
> +  public async createIngestionTask(
method name is unclear, i would suggest 'createTilesSplittingTask'

2022-05-17 09:32 UTC, asafMasa commented on src/layers/models/tasker.ts
> +          jobId = await this.db.createLayerJob(data, layerRelativePath, jobType, taskBatch);
send configured task type to method

2022-05-17 09:32 UTC, asafMasa commented on src/layers/models/tasker.ts
> +            await this.db.createTasks(jobId, taskBatch);
send configured task type to method

2022-05-18 06:41 UTC, CL-SHLOMIKONCHA commented on src/common/interfaces.ts
> +}
fixed

2022-05-18 06:59 UTC, CL-SHLOMIKONCHA commented on package.json
> +    "better-sqlite3": "^7.5.1",
removed

2022-05-18 06:59 UTC, CL-SHLOMIKONCHA commented on package.json
> +    "ansi-regex": "^6.0.1",
removed

2022-05-18 07:00 UTC, CL-SHLOMIKONCHA commented on src/common/interfaces.ts
> +}
fixed

2022-05-18 07:01 UTC, CL-SHLOMIKONCHA commented on package.json
> +    "@types/better-sqlite3": "^7.5.0",
removed

2022-05-18 13:19 UTC, CL-SHLOMIKONCHA commented on src/common/interfaces.ts
> -
fixed

2022-05-18 13:19 UTC, CL-SHLOMIKONCHA commented on src/serviceClients/jobManagerClient.ts
> +        type: TaskType.MERGE,
fixed

2022-05-18 13:20 UTC, CL-SHLOMIKONCHA commented on src/layers/models/tasker.ts
> +  public async createIngestionTask(
fixed

2022-05-18 13:20 UTC, CL-SHLOMIKONCHA commented on src/layers/models/tasker.ts
> +          jobId = await this.db.createLayerJob(data, layerRelativePath, jobType, taskBatch);
fixed

2022-05-18 13:20 UTC, CL-SHLOMIKONCHA commented on src/layers/models/tasker.ts
> +            await this.db.createTasks(jobId, taskBatch);
fixed

2022-05-18 13:21 UTC, CL-SHLOMIKONCHA commented on src/layers/models/fileValidator.ts
> +    const filePromises = files.map((file) => {
fixed

2022-05-18 13:22 UTC, CL-SHLOMIKONCHA commented on src/layers/models/layersManager.ts
> +    await this.validateNotExistsInMapServer(resourceId, productType);
fixed - moved only to "New" ingestion job logic

2022-05-18 13:22 UTC, CL-SHLOMIKONCHA commented on src/layers/models/layersManager.ts
> +    await this.createTasks(data, layerRelativePath, layerZoomRanges, jobType);
fixed

2022-05-18 13:23 UTC, CL-SHLOMIKONCHA commented on src/layers/models/tasker.ts
> +import { JobType, OperationStatus } from '../../common/enums';
fixed

2022-05-18 13:26 UTC, CL-SHLOMIKONCHA commented on src/serviceClients/jobManagerClient.ts
>  const jobType = config.get<string>('jobType');
fixed

2022-05-19 06:11 UTC, CL-SHLOMIKONCHA commented on src/layers/models/tasker.ts
> +    this.tasksBatchSize = config.get<number>('tasksBatchSize');
fixed

2022-05-19 06:29 UTC, CL-SHLOMIKONCHA commented on src/common/enums.ts
> +  MERGE = 'Merge',
fixed

2022-05-19 06:30 UTC, CL-SHLOMIKONCHA commented on src/layers/models/layersManager.ts
> +    await this.validateNotRunning(resourceId, version, productType, jobType);
fixed

2022-05-19 06:31 UTC, CL-SHLOMIKONCHA commented on src/layers/models/layersManager.ts
> +      const allValidGpkgs = await this.fileValidator.validateGpkgFiles(data.fileNames);
fixed

2022-05-19 06:37 UTC, CL-SHLOMIKONCHA commented on src/common/enums.ts
> +  DISCRETE_TILING = 'Discrete-Tiling',
fixed

2022-05-19 06:37 UTC, CL-SHLOMIKONCHA commented on tests/unit/layers/models/tasker.spec.ts
> +import { JobType } from '../../../../src/common/enums';
fixed

2022-05-19 10:09 UTC, CL-SHLOMIKONCHA commented on tests/unit/layers/models/layersModel.spec.ts
> +    it('saves metadata before queueing ingestion tasks', async function () {
fixed

2022-05-19 10:09 UTC, CL-SHLOMIKONCHA commented on tests/unit/merger/mergeTasker.spec.ts
> +    // it('same footprint', () => {
fixed

2022-05-19 10:10 UTC, CL-SHLOMIKONCHA commented on tests/unit/layers/models/tasker.spec.ts
> +  describe('createIngestionTask', () => {
fixed

2022-05-19 14:28 UTC, asafMasa requested changes

2022-05-19 14:28 UTC, asafMasa commented on src/layers/models/splitTilesTasker.ts
> +    this.setDefaultValues(data);
move back to layers manager

2022-05-19 14:28 UTC, asafMasa commented on src/merge/mergeTilesTasker.ts
> +    const sourceDir = this.config.get<string>('LayerSourceDir');
move the config values reading to constructor

2022-05-19 14:28 UTC, asafMasa commented on src/merge/mergeTilesTasker.ts
> +          jobId = await this.db.createLayerJob(data, layerRelativePath, jobType, this.mergeTilesTaskType, mergeTaskBatch);
add task type here

2022-05-19 14:28 UTC, asafMasa commented on src/merge/mergeTilesTasker.ts
> +            await this.db.createMergeTasks(jobId, mergeTaskBatch);
add task type here

2022-05-19 14:28 UTC, asafMasa commented on src/merge/mergeTilesTasker.ts
> +        jobId = await this.db.createLayerJob(data, layerRelativePath, jobType, this.mergeTilesTaskType, mergeTaskBatch);
add task type here

2022-05-19 14:28 UTC, asafMasa commented on src/merge/mergeTilesTasker.ts
> +          await this.db.createMergeTasks(jobId, mergeTaskBatch);
add task type here

2022-05-19 14:28 UTC, asafMasa commented on src/serviceClients/jobManagerClient.ts
> +const ingestionNewTaskType = config.get<string>('ingestionNewTaskType');
?

2022-05-19 14:28 UTC, asafMasa commented on src/serviceClients/jobManagerClient.ts
> +        type: ingestionNewTaskType,
get it from method args

2022-05-19 14:28 UTC, asafMasa commented on src/serviceClients/jobManagerClient.ts
> +  public async createMergeTasks(jobId: string, taskParams: IMergeTaskParams[]): Promise<void> {
duplicated method - remove

2022-05-19 14:58 UTC, asafMasa commented on tests/integration/layers/layers.spec.ts
> +    setValue('ingestionNewTiles.tasksBatchSize', 2);
fix LGTM warnings
split tasker
![image](https://user-images.githubusercontent.com/18442671/169326956-50d1f7d5-2f9a-4a0e-9559-7f5dcfc71e05.png)

merge tasker
![image](https://user-images.githubusercontent.com/18442671/169327228-0342f1ca-4708-44f1-b0ec-b51265d3935c.png)

2022-05-22 15:15 UTC, asafMasa requested changes
looking better, but i still have more changes...
mind some of my old remarks weren't resolved

2022-05-22 15:15 UTC, asafMasa commented on src/layers/models/layersManager.ts
> +      await this.validateNotExistsInCatalog(resourceId, version, productType);
move validations first, no need to call "createLayerZoomRanges" if the operation isn't valid

2022-05-22 15:15 UTC, asafMasa commented on src/layers/models/layersManager.ts
> +    } else if (jobType === JobType.UPDATE) {
if you already added the else if, add else {
.. throw unsupported jobType 
}

2022-05-24 13:13 UTC, asafMasa requested changes

2022-05-24 14:55 UTC, merged