chore: validate geopackage index
MapColonies/discrete-overseer-creator pull request #140
Opened 2022-06-01 12:19 UTC by CL-SHLOMIKONCHA

| Question                | Answer                                                                          |
| ---------------- | -------------------------------------------------------------------------- |
| Bug fix         | ✔/✖                                                                        |
| New feature     | ✔/✖                                                                        |
| Breaking change | ✔/✖                                                                        |
| Deprecations    | ✔/✖                                                                        |
| Documentation   | ✔/✖                                                                        |
| Tests added     | ✔/✖                                                                        |
| Chore            | ✔/✖                                                                       |

Related issues: #XXX , #XXX ...
Closes #XXX ...

Further  information:

2022-06-02 09:54 UTC, asafMasa requested changes

2022-06-02 09:54 UTC, asafMasa commented on src/layers/models/fileValidator.ts
> +    const allValid = this.validateGpkgExtension(files);
validate extension should be called before "validateGpkgIndex" 

const isExtensionValid = this.validateGpkgExtension(files);
if (!isExtensionValid) {
return false }
... validateGpkgIndex()

2022-06-02 09:54 UTC, asafMasa commented on src/layers/models/layersManager.ts
>      await this.validateJobNotRunning(resourceId, productType);
move the "validateJobNotRunning" method before the "getJobType" function

2022-06-02 09:54 UTC, asafMasa commented on src/serviceClients/sqliteClient.ts
> +    this.db = new Database(this.fullPath, { fileMustExist: true });
this row opens the DB connection - https://github.com/WiseLibs/better-sqlite3/blob/HEAD/docs/api.md#new-databasepath-options

you should move it inside the "getGpkgIndex()" method

2022-06-02 09:54 UTC, asafMasa commented on src/serviceClients/sqliteClient.ts
> +    this.closeConnection();
add try, finally to the method content, in the finally close the db connection

2022-06-02 09:58 UTC, asafMasa requested changes

2022-06-02 09:58 UTC, asafMasa commented on tests/unit/layers/models/fileValidator.spec.ts
> +      const testData: string[] = ['no-index.gpkg'];
you can create the index with mock and add a test for existing index (valid response)

a file with invalid GPKG can be added to the integration tests

2022-06-06 06:54 UTC, CL-SHLOMIKONCHA commented on src/layers/models/fileValidator.ts
> +    const allValid = this.validateGpkgExtension(files);
fixed

2022-06-06 07:01 UTC, CL-SHLOMIKONCHA commented on src/layers/models/layersManager.ts
>      await this.validateJobNotRunning(resourceId, productType);
fixed

2022-06-06 07:08 UTC, CL-SHLOMIKONCHA commented on src/serviceClients/sqliteClient.ts
> +    this.closeConnection();
fixed

2022-06-06 14:49 UTC, CL-SHLOMIKONCHA commented on src/serviceClients/sqliteClient.ts
> +    this.db = new Database(this.fullPath, { fileMustExist: true });
fixed

2022-06-06 14:49 UTC, CL-SHLOMIKONCHA commented on tests/unit/layers/models/fileValidator.spec.ts
> +      const testData: string[] = ['no-index.gpkg'];
fixed - added integration tests

2022-06-07 07:48 UTC, asafMasa requested changes

2022-06-07 07:48 UTC, asafMasa commented on tests/unit/layers/models/fileValidator.spec.ts
> +      const testData: string[] = ['unndexed.gpkg'];
spelling, remove no-index

2022-06-07 08:28 UTC, CL-SHLOMIKONCHA commented on src/serviceClients/sqliteClient.ts
> +    const db = new Database(this.fullPath, { fileMustExist: true });
fixed

2022-06-07 08:28 UTC, CL-SHLOMIKONCHA commented on tests/unit/layers/models/fileValidator.spec.ts
> +      const testData: string[] = ['unndexed.gpkg'];
fixed

2022-06-07 09:22 UTC, asafMasa requested changes
fix lint

2022-06-07 09:22 UTC, asafMasa commented on src/serviceClients/sqliteClient.ts
> +      this.db = new Database(this.fullPath, { fileMustExist: true });
no need for it to be a class member
let db?: SQLiteDB;
try { 
db = new Database(this.fullPath, { fileMustExist: true });
...
}  finally {
 if(db) {
        db.close();
      }
}

2022-06-07 11:40 UTC, asafMasa approved these changes

2022-06-07 11:58 UTC, CL-SHLOMIKONCHA commented on src/serviceClients/sqliteClient.ts
> +      this.db = new Database(this.fullPath, { fileMustExist: true });
fixed

2022-06-07 12:02 UTC, merged