chore: add finish merge logic
MapColonies/discrete-overseer-creator pull request #142
Opened 2022-06-08 07:38 UTC by AnguIar

2022-06-09 14:47 UTC, asafMasa requested changes
👍

2022-06-09 14:47 UTC, asafMasa commented on src/tasks/models/tasksManager.ts
> +        const layerName = getMapServingLayerName(job.metadata.productId as string, job.metadata.productType as ProductType);
add appropriate log message

2022-06-09 14:47 UTC, asafMasa commented on src/tasks/models/tasksManager.ts
> +        this.logger.log(
add the if job not completed and task failed - abortJob logic

2022-06-09 14:47 UTC, asafMasa commented on src/tasks/models/tasksManager.ts
> +      if (job.completedTasksCount === 0) {
i don't know if this condition is valid as worker might update it's status to completed before calling the overseer - need to check with tiles splitter and tiles merger implementations.
as you use the job.task statuses i don't think it will be 0
and due to the async nature of the tasks you can't assume 1 either

2022-06-09 14:47 UTC, asafMasa commented on src/tasks/models/tasksManager.ts
> +      const catalogRecord = await this.catalogClient.findRecord(
as the merger code is valid for new ingestion and an update - you need to separate the code here - unify metadata only for the update, and i don't see the insert to mapProxy, insert to catalog and sync methods (refactor to one method to be called from both logics)

2022-06-09 14:47 UTC, asafMasa commented on src/tasks/models/tasksManager.ts
> +    if (task.status === OperationStatus.FAILED) {
add appropriate log messages

2022-06-09 14:47 UTC, asafMasa commented on src/toc/models/tocManager.ts
> +      const data = await this.client.findRecord(params.productId, params.productVersion, params.productType);
you have changed the response type

2022-06-09 14:47 UTC, asafMasa commented on tests/unit/tasks/models/tasksModel.spec.ts
> +    it('should abort all merge tasks and make job failed on task failure', async function () {
for new job - split
for new job - merge
for update job - merge

2022-06-09 14:47 UTC, asafMasa commented on tests/unit/tasks/models/tasksModel.spec.ts
> +    it('should complete job once all tasks are successful', async function () {
for new job - split
for new job - merge
for update job - merge
as they have different logics

2022-06-12 06:51 UTC, AnguIar commented on src/tasks/models/tasksManager.ts
> +      await this.handleSplitTask(job, task);
Method not allowed is used for HTTP methods (get, post, put)...

2022-06-12 15:21 UTC, asafMasa requested changes

2022-06-12 15:21 UTC, asafMasa commented on src/tasks/models/tasksManager.ts
>        await this.handleMergeTask(job, task);
rename handleMergeTask as there is a scenario of merge task that is not handled here

2022-06-12 15:21 UTC, asafMasa commented on src/tasks/models/tasksManager.ts
> +        this.logger.log(`info`, `Merging metadata of ${job.id} with metadata from catalog record ${catalogRecord?.id as string}`);
put the log before the line
 const mergedData = this.metadataMerger.merge(job.metadata, catalogRecord?.metadata as LayerMetadata);

2022-06-13 08:04 UTC, AnguIar commented on src/tasks/models/tasksManager.ts
> +      this.logger.log(`info`, `[TasksManager][taskComplete] Completing merge task with jobId ${jobId} and taskId ${taskId}.`);
What's wrong with this log?

2022-06-13 08:06 UTC, AnguIar commented on src/tasks/models/tasksManager.ts
> +      this.logger.log(`info`, `[TasksManager][taskComplete] Completing merge task with jobId ${jobId} and taskId ${taskId}.`);
what's wrong with this log?

2022-06-13 08:06 UTC, AnguIar commented on src/tasks/models/tasksManager.ts
> +      this.logger.log(`info`, `[TasksManager][taskComplete] Completing tiles-splitting task with jobId ${jobId} and taskId ${taskId}.`);
what's wrong with this log?

2022-06-13 13:08 UTC, asafMasa requested changes

2022-06-13 13:08 UTC, asafMasa commented on src/tasks/models/tasksManager.ts
> +      if (job.successTasksCount === 0) {
i don't know if this condition is valid as worker might update it's status to completed before calling the overseer - need to check with tiles splitter and tiles merger implementations.
as you use the job.task statuses i don't think it will be 0
and due to the async nature of the tasks you can't assume 1 either

2022-06-21 14:32 UTC, asafMasa approved these changes

2022-06-21 14:32 UTC, merged