chore: added node affinity
MapColonies/discrete-overseer-creator pull request #150
Opened 2022-07-21 08:56 UTC by CL-SHLOMIKONCHA

| Question                | Answer                                                                          |
| ---------------- | -------------------------------------------------------------------------- |
| Bug fix         | ✔/✖                                                                        |
| New feature     | ✔/✖                                                                        |
| Breaking change | ✔/✖                                                                        |
| Deprecations    | ✔/✖                                                                        |
| Documentation   | ✔/✖                                                                        |
| Tests added     | ✔/✖                                                                        |
| Chore            | ✔/✖                                                                       |

Related issues: #XXX , #XXX ...
Closes #XXX ...

Further  information:

2022-07-24 13:32 UTC, asafMasa approved these changes

2022-07-24 13:39 UTC, asafMasa requested changes

2022-07-24 13:39 UTC, asafMasa commented on helm/values.yaml
> +  useNodeAffinity: true
default false

2022-07-25 07:46 UTC, CL-SHLOMIKONCHA commented on helm/values.yaml
> +  useNodeAffinity: true
fixed

2022-07-25 08:57 UTC, asafMasa approved these changes

2022-07-25 09:04 UTC, merged