fix: error code on not valid layer version
MapColonies/discrete-overseer-creator pull request #168
Opened 2022-09-06 12:59 UTC by ronenkapelian

| Question                | Answer                                                                          |
| ---------------- | -------------------------------------------------------------------------- |
| Bug fix         | ✔                                                                      |
| New feature     | ✖                                                                        |
| Breaking change | ✖                                                                        |
| Deprecations    | ✖                                                                        |
| Documentation   | ✖                                                                        |
| Tests added     | ✖                                                                        |
| Chore            | ✖                                                                       |

Related issues: #XXX , #XXX ...
Closes #XXX ...

Further  information:

2022-09-06 13:25 UTC, asafMasa requested changes
👍

2022-09-06 13:25 UTC, asafMasa commented on src/layers/models/layersManager.ts
> +        `layer id: ${resourceId} version: ${version} product type: ${productType} has already the same version (${highestExistsLayerVersion}) in catalog`
add tests for each condition

2022-09-06 13:25 UTC, asafMasa commented on src/layers/models/layersManager.ts
> +      console.log('blabla**********************')
remove

2022-09-06 13:25 UTC, asafMasa commented on src/layers/models/layersManager.ts
> +    if (requestedLayerVersion === highestExistsLayerVersion) {
fix Prettier

2022-09-07 08:10 UTC, ronenkapelian commented on src/layers/models/layersManager.ts
> +    if (requestedLayerVersion === highestExistsLayerVersion) {
done

2022-09-07 08:10 UTC, ronenkapelian commented on src/layers/models/layersManager.ts
> +      console.log('blabla**********************')
done

2022-09-07 08:10 UTC, ronenkapelian commented on src/layers/models/layersManager.ts
> +        `layer id: ${resourceId} version: ${version} product type: ${productType} has already the same version (${highestExistsLayerVersion}) in catalog`
done -> 2 relevant new tests to check the logic

2022-09-07 10:27 UTC, asafMasa approved these changes

2022-09-07 10:27 UTC, merged