chore: added catalogId and displayPath support
MapColonies/discrete-overseer-creator pull request #170
Opened 2022-09-18 11:37 UTC by CL-SHLOMIKONCHA

| Question                | Answer                                                                          |
| ---------------- | -------------------------------------------------------------------------- |
| Bug fix         | ✔/✖                                                                        |
| New feature     | ✔/✖                                                                        |
| Breaking change | ✔/✖                                                                        |
| Deprecations    | ✔/✖                                                                        |
| Documentation   | ✔/✖                                                                        |
| Tests added     | ✔/✖                                                                        |
| Chore            | ✔/✖                                                                       |

Related issues: #XXX , #XXX ...
Closes #XXX ...

Further  information:

2022-09-18 12:49 UTC, asafMasa requested changes

2022-09-18 12:49 UTC, asafMasa commented on package.json
> +    "@map-colonies/mc-model-types": "file:../mc-models/map-colonies-mc-model-types-13.1.3.tgz",
update to real package before merging

2022-09-18 12:49 UTC, asafMasa commented on src/layers/models/layersManager.ts
> +    let id: string;
1. Add generate catalog id log
2. Add try catch and on exception throw failed to generate catalog id message

2022-09-18 12:49 UTC, asafMasa commented on src/layers/models/layersManager.ts
> +      isExists = await this.catalog.existsByRecordId(id);
probably overkill, but add validation against in progress / pending "new" ingestion jobs "catalogId fields"

2022-09-18 12:51 UTC, asafMasa commented on src/layers/models/layersManager.ts
> +      isExists = await this.catalog.existsByRecordId(id);
Fix lint and tests

2022-09-19 05:48 UTC, cl-shaharshavit-rnd requested changes

2022-09-19 05:48 UTC, cl-shaharshavit-rnd commented on src/layers/models/layersManager.ts
> +        this.logger.log('info', `generating record id`);
should probably be debug log

2022-09-19 05:48 UTC, cl-shaharshavit-rnd commented on package.json
> +    "@map-colonies/mc-model-types": "file:../mc-models/map-colonies-mc-model-types-13.1.3.tgz",
don't forget to replace that with published version

2022-09-21 13:56 UTC, cl-shaharshavit-rnd requested changes

2022-09-21 13:56 UTC, cl-shaharshavit-rnd commented on src/serviceClients/sqliteClient.ts
> +    @inject(Services.CONFIG) private readonly config: IConfig,
remove injects

2022-09-21 13:56 UTC, cl-shaharshavit-rnd commented on src/serviceClients/sqliteClient.ts
> +@singleton()
remove singleton

2022-09-21 13:56 UTC, cl-shaharshavit-rnd commented on tests/unit/serviceClients/sqliteClient.spec.ts
> +      //const testDb = new SQLiteClient(config, logger, 'test.gpkg', '/here');
remove

2022-09-21 13:59 UTC, cl-shaharshavit-rnd approved these changes

2022-09-21 14:45 UTC, asafMasa approved these changes

2022-09-21 15:07 UTC, merged