feat!: adding transparency and tile output format params (MAPCO-2580)
MapColonies/discrete-overseer-creator pull request #185
Opened 2022-12-25 14:44 UTC by ronenkapelian

| Question                | Answer                                                                          |
| ---------------- | -------------------------------------------------------------------------- |
| Bug fix         | ✖                                                                        |
| New feature     | ✔                                                                        |
| Breaking change | ✔                                                                        |
| Deprecations    | ✖                                                                        |
| Documentation   | ✖                                                                        |
| Tests added     | ✔                                                                        |
| Chore            | ✔                                                                       |

Bumping mc-models major version to 14.0.0
it include 2 new fields:

* Transparency as mandatory field and pycsw field (TRANSPARENT | OPAQUE)
* TileOutputFormat as mandatory internal and self-calculated fields (PNG | JPEG)

2022-12-25 15:06 UTC, asafMasa requested changes
👍 Good job

2022-12-25 15:06 UTC, asafMasa commented on src/merge/mergeTilesTasker.ts
> +            targetFormat: params.targetFormat,
delete TargetFormat from enums

2022-12-25 15:21 UTC, ronenkapelian commented on src/merge/mergeTilesTasker.ts
> +            targetFormat: params.targetFormat,
done

2022-12-26 10:33 UTC, asafMasa commented
https://github.com/MapColonies/discrete-overseer-creator/blob/master/src/tasks/models/tasksManager.ts#L102
This is hard coded - need to be set by tiles format value

2022-12-26 10:36 UTC, asafMasa commented
Check that https://github.com/MapColonies/discrete-overseer-creator/blob/master/tests/unit/tasks/models/tasksModel.spec.ts#L44 changes by tile format value

2022-12-26 10:42 UTC, asafMasa commented
https://github.com/MapColonies/discrete-overseer-creator/blob/master/src/layers/interfaces.ts#L2 why? please check that its not repeated

2022-12-27 06:37 UTC, asafMasa approved these changes

2022-12-27 08:40 UTC, merged