feat: adding prom-client metrics + basic metrics
MapColonies/discrete-overseer-creator pull request #22
Opened 2023-08-17 11:17 UTC by ronenkapelian

| Question                | Answer                                                                          |
| ---------------- | -------------------------------------------------------------------------- |
| Bug fix         | ✖                                                                        |
| New feature     | ✔                                                                        |
| Breaking change | ✖                                                                        |
| Deprecations    | ✖                                                                        |
| Documentation   | ✖                                                                        |
| Tests added     | ✖                                                                        |
| Chore            | ✔                                                                      |

was added implementation for prom-client libary:

1. added required endpoint (/metrics)
2. adding 3 base metrics:
  a. counter for success ingestion jpbs creation
  b. histogram for timings of success ingestions
  c. seperate histogram for update\new and 
      merger\splitter types
3. include todo remarks to deal with tasker (splitter + merging) on future after code refactoring
4. helm + config adjustment to be supported on openshift deployment

2023-08-17 15:13 UTC, asafMasa requested changes
Good job 👍

2023-08-17 15:13 UTC, asafMasa commented on config/default.json
> +      "enabled": true,
check that enabled false works

2023-08-17 15:13 UTC, asafMasa commented on config/default.json
> +    "metrics": {
please make sure all values in "custom-environment-variables.json" exists in "default.json" file

2023-08-17 15:13 UTC, asafMasa commented on config/default.json
> +    "projectName": "discrete-overseer-creator"
shouldn't it be in "telemetry" section?

2023-08-17 15:13 UTC, asafMasa commented on config/default.json
> +      "buckets": [0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1, 2.5, 5, 10, 15, 50, 250, 500]
Shouldn't it be in helm values?

2023-08-17 15:13 UTC, asafMasa commented on src/containerConfig.ts
>  import { DependencyContainer } from 'tsyringe/dist/typings/types';
check if this dependecy is needed.

2023-08-17 15:13 UTC, asafMasa commented on src/containerConfig.ts
> +              project: config.get('app.projectName'),
why don't you use SERVICE_NAME?

2023-08-17 15:13 UTC, asafMasa commented on src/layers/models/layersManager.ts
> +      if (fetchTimerEnd) {
move to after the else {} closer and remove duplication

2023-08-17 15:13 UTC, asafMasa commented on src/layers/models/layersManager.ts
> +    let successCreatingJobTask = true; // if create job task metric completed successfully
not needed

2023-08-17 15:13 UTC, asafMasa commented on src/layers/models/layersManager.ts
> +
try catch as discussed

2023-08-17 15:13 UTC, asafMasa commented on src/layers/models/layersManager.ts
>          jobId = await this.mergeTilesTasker.createMergeTilesTasks(data, layerRelativePath, taskType, jobType, this.grids, extent, overseerUrl, true);
try catch on this method, catch will throw
only for success
same histogram for new and update (of tiles merge tasker)

2023-08-17 15:13 UTC, asafMasa commented on src/layers/models/layersManager.ts
>          const layerZoomRanges = this.zoomLevelCalculator.createLayerZoomRanges(data.metadata.maxResolutionDeg as number);
try catch on this method, catch will throw
only for success

2023-08-17 15:13 UTC, asafMasa commented on src/layers/models/layersManager.ts
>          jobId = await this.mergeTilesTasker.createMergeTilesTasks(data, layerRelativePath, taskType, jobType, this.grids, extent, overseerUrl, true);
Check if can be aggregated by zoom and square kilometer(km^2) - for splitter also

2023-08-22 12:47 UTC, ronenkapelian commented on config/default.json
> +    "metrics": {
done

2023-08-22 12:52 UTC, ronenkapelian commented on config/default.json
> +      "enabled": true,
done - should be validate after merging - evaluation on openshift with helm

2023-08-24 06:58 UTC, ronenkapelian commented on config/default.json
> +      "buckets": [0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1, 2.5, 5, 10, 15, 50, 250, 500]
added

2023-08-24 07:03 UTC, ronenkapelian commented on src/containerConfig.ts
>  import { DependencyContainer } from 'tsyringe/dist/typings/types';
it's in use for typing ( checked also with npm run lint: fix that usually marks unused importing)

2023-08-24 07:04 UTC, ronenkapelian commented on src/containerConfig.ts
> +              project: config.get('app.projectName'),
replaced

2023-08-24 07:04 UTC, ronenkapelian commented on src/layers/models/layersManager.ts
> +    let successCreatingJobTask = true; // if create job task metric completed successfully
removed

2023-08-24 07:05 UTC, ronenkapelian commented on src/layers/models/layersManager.ts
> +
done

2023-08-24 07:06 UTC, ronenkapelian commented on src/layers/models/layersManager.ts
>          jobId = await this.mergeTilesTasker.createMergeTilesTasks(data, layerRelativePath, taskType, jobType, this.grids, extent, overseerUrl, true);
we discuess about it, should consider design and future implemntation that suitable for it. it too much data for metrics purpose

2023-08-24 07:07 UTC, ronenkapelian commented on src/layers/models/layersManager.ts
>          const layerZoomRanges = this.zoomLevelCalculator.createLayerZoomRanges(data.metadata.maxResolutionDeg as number);
done

2023-08-24 07:07 UTC, ronenkapelian commented on src/layers/models/layersManager.ts
> +      if (fetchTimerEnd) {
done

2023-08-24 10:46 UTC, asafMasa requested changes
😎 looking good. please mind my changes

2023-08-24 10:46 UTC, asafMasa commented on src/containerConfig.ts
> +        useFactory: instancePerContainerCachingFactory((container) => {
Why did you use "instancePerContainerCachingFactory" and not "instanceCachingFactory"?

2023-08-24 10:46 UTC, asafMasa commented on src/layers/models/layersManager.ts
> +          fetchTimerTotalJobsEnd();
Why dont you close it after the catch? (or in the catch if you wan failures?)

2023-08-24 10:46 UTC, asafMasa commented on src/layers/models/layersManager.ts
> +    const fetchTimerEnd = this.createJobTasksHistogram?.startTimer({ requestType: 'CreateLayer', jobType, taskType });
the "fetchTimerEnd" isn't self explanatory

2023-08-24 10:46 UTC, asafMasa commented on src/layers/models/layersManager.ts
> +    const fetchTimerTotalJobsEnd = this.createJobTasksTotalHistogram?.startTimer({ requestType: 'CreateLayer' });
as "fetchTimerTotalJobsEnd" and "fetchTimerEnd" measure the same time, why do we split between them?

2023-08-24 10:55 UTC, asafMasa commented on src/layers/models/layersManager.ts
> +    const fetchTimerTotalJobsEnd = this.createJobTasksTotalHistogram?.startTimer({ requestType: 'CreateLayer' });
Add dashboard json config under assets

2023-08-24 13:16 UTC, asafMasa approved these changes

2023-08-24 13:36 UTC, merged