feat: adding format (mime-type) + upgrade mc-models + types
MapColonies/discrete-overseer-creator pull request #25
Opened 2023-10-02 12:36 UTC by ronenkapelian

Implement Overseer to support and provide Format (Mime) for image on records

| Question                | Answer                                                                          |
| ---------------- | -------------------------------------------------------------------------- |
| Bug fix         | ✖                                                                        |
| New feature     | ✔                                                                       |
| Breaking change | ✖                                                                        |
| Deprecations    | ✖                                                                        |
| Documentation   | ✖                                                                        |
| Tests added     | ✔                                                                        |
| Chore            | ✖                                                                       |

* Added new attribiurte called format
format is string posiible values (image/png | image/jpeg).
* field calculated by source data and reflected from lookup provided from types package
* upgrade CI node versions (18-20)

2023-10-08 09:43 UTC, asafMasa requested changes
Good Job!

2023-10-08 09:43 UTC, asafMasa commented on .github/workflows/pull_request.yaml
> -          node-version: 16
docker file is set to 16 please update it to ts-server boiler plate version (20),  same as with the workflow file

2023-10-08 09:43 UTC, asafMasa commented on src/layers/models/layersManager.ts
> +        const message = `Update job - Transparency, TileOutputFormat and TilesMimeFormat will be override from catalog:
Send the "tileMimeFormat" to mapproxy-api instead of "tileOutputFormat"

2024-02-20 14:05 UTC, closed without merging

2024-02-20 14:06 UTC, ronenkapelian commented
deprecated