fix: add feature to block parallel ingestion from the same layer
MapColonies/discrete-overseer-creator pull request #27
Opened 2023-10-24 11:08 UTC by razbroc

| Question                | Answer                                                                          |
| ---------------- | -------------------------------------------------------------------------- |
| Bug fix         | ✔                                                                        |
| New feature     | ✖                                                                        |
| Breaking change | ✔                                                                        |
| Deprecations    | ✖                                                                        |
| Documentation   | ✖                                                                        |
| Tests added     | ✖                                                                        |
| Chore            | ✔                                                                       |

2023-10-24 13:21 UTC, asafMasa requested changes
Good Job, Please mind my remarks 👍

2023-10-24 13:21 UTC, asafMasa commented on src/layers/models/layersManager.ts
> +        job.status == OperationStatus.IN_PROGRESS ||
This is a bug you need to check 
(job.status == OperationStatus.IN_PROGRESS || job.status == OperationStatus.PENDING) && ingestionJobTypes.indexOf(job.type) == notFoundIndex

2023-10-24 13:21 UTC, asafMasa commented on src/layers/models/layersManager.ts
> +    const ingestionJobTypes = this.config.get<string[]>('forbiddenTypesForParallelIngesion');
check if this is being overriden from helm values

2023-10-25 07:01 UTC, razbroc commented on src/layers/models/layersManager.ts
> +    const ingestionJobTypes = this.config.get<string[]>('forbiddenTypesForParallelIngesion');
values from helm are transferred fine :)

2023-10-25 07:04 UTC, razbroc commented on src/layers/models/layersManager.ts
> +        job.status == OperationStatus.IN_PROGRESS ||
if the job for this layer is ingestion, and it's pending or in progress throw ConflictError.
can you explain further what you meant?

2023-10-25 07:04 UTC, razbroc commented on src/layers/models/layersManager.ts
> +    const ingestionJobTypes = this.config.get<string[]>('forbiddenTypesForParallelIngesion');
![image](https://github.com/MapColonies/discrete-overseer-creator/assets/77406876/d3dc53eb-072b-41bb-ae5b-1eb70d6f98d2)

2023-10-25 08:04 UTC, asafMasa commented on helm/values.yaml
> +  forbiddenTypesForParallelIngesion:
add values to raster helm

2023-10-25 16:21 UTC, razbroc commented on src/layers/models/layersManager.ts
> +    const ingestionJobTypes = this.config.get<string[]>('forbiddenTypesForParallelIngesion');
checked it is good

2023-10-25 16:28 UTC, razbroc commented on helm/values.yaml
> +  forbiddenTypesForParallelIngesion:
https://github.com/MapColonies/raster-helm/pull/416

2023-10-26 07:11 UTC, asafMasa requested changes
Good Job - looking good 😎 
Please mind my remarks

2023-10-26 07:11 UTC, asafMasa commented on src/layers/models/layersManager.ts
>          const message = `Layer id: ${productId} product type: ${productType}, job is already running`;
`Layer id: ${productId} product type: ${productType}, conflicting job ${ingestionJobTypes[0]} is already running`

2023-10-26 07:11 UTC, asafMasa commented on tests/integration/layers/layers.spec.ts
> +      const jobs = [
add a test for export jobType - that it's valid

2023-10-26 07:11 UTC, asafMasa commented on tests/unit/layers/models/layersManager.spec.ts
> +      getJobsMock.mockResolvedValue([{ status: OperationStatus.PENDING, type: 'Ingestion_New' }]);
add a test for export jobType - that it's valid

2023-10-26 07:11 UTC, asafMasa commented on tests/integration/layers/layers.spec.ts
> +        { status: OperationStatus.IN_PROGRESS, type: 'Ingestion_New' },
Check that we have a test for Aborted and Expired (ingestion) jobs

2023-10-26 07:52 UTC, razbroc commented on src/layers/models/layersManager.ts
>          const message = `Layer id: ${productId} product type: ${productType}, job is already running`;
changed

2023-10-26 08:02 UTC, razbroc commented on tests/integration/layers/layers.spec.ts
> +      const jobs = [
added

2023-10-26 08:10 UTC, razbroc commented on tests/integration/layers/layers.spec.ts
> +        { status: OperationStatus.IN_PROGRESS, type: 'Ingestion_New' },
added

2023-10-26 08:11 UTC, razbroc commented on tests/unit/layers/models/layersManager.spec.ts
> +      getJobsMock.mockResolvedValue([{ status: OperationStatus.PENDING, type: 'Ingestion_New' }]);
added

2023-10-26 12:24 UTC, asafMasa requested changes

2023-10-26 12:24 UTC, asafMasa commented on tests/integration/layers/layers.spec.ts
> +    it('should return 409 if rested layer is already being generated while also having aborted job', async function () {
rested -> rename to tested

2023-10-26 12:24 UTC, asafMasa commented on tests/integration/layers/layers.spec.ts
> +    it('should return 409 if rested layer is already being generated while also having aborted job', async function () {
"generated" change to "In-Progress"

2023-10-26 12:24 UTC, asafMasa commented on tests/integration/layers/layers.spec.ts
> +    it('should return 409 if rested layer is already being generated while also having expired job', async function () {
rested -> "tested"

2023-10-26 12:57 UTC, asafMasa approved these changes

2023-10-26 14:18 UTC, merged