fix: update metadata on successfull end of update process (MAPCO-3528)
MapColonies/discrete-overseer-creator pull request #28
Opened 2023-10-29 08:56 UTC by razbroc

| Question                | Answer                                                                          |
| ---------------- | -------------------------------------------------------------------------- |
| Bug fix         | ✔                                                                        |
| New feature     | ✔                                                                        |
| Breaking change | ✖                                                                        |
| Deprecations    | ✖                                                                        |
| Documentation   | ✖                                                                        |
| Tests added     | ✖                                                                        |
| Chore            | ✔                                                                       |

2023-10-30 11:19 UTC, asafMasa requested changes
👍

2023-10-30 11:19 UTC, asafMasa commented on src/jobs/models/jobsManager.ts
> +        const mergedData = this.metadataMerger.merge(catalogRecord.metadata, job.metadata);
before previous action (job update)

2023-10-30 11:19 UTC, asafMasa commented on tests/unit/tasks/models/jobsModel.spec.ts
> +      expect(mergeMock).toHaveBeenCalledTimes(0);
check if this is being checked on job completion

2023-11-03 06:27 UTC, razbroc commented on tests/unit/tasks/models/jobsModel.spec.ts
> +      expect(mergeMock).toHaveBeenCalledTimes(0);
on test `it('should complete job once all tasks are successful for update-merge job-task'`

2023-11-03 06:28 UTC, razbroc commented on tests/unit/tasks/models/jobsModel.spec.ts
> +      expect(mergeMock).toHaveBeenCalledTimes(0);
`      expect(updateMock).toHaveBeenCalledTimes(1);`

2023-11-06 12:36 UTC, asafMasa approved these changes

2023-11-06 12:37 UTC, merged