feat(server): added layers controller skeleton
MapColonies/discrete-overseer-creator pull request #6
Opened 2021-01-11 14:21 UTC by cl-shaharshavit-rnd

| Question                | Answer                                                                          |
| ---------------- | -------------------------------------------------------------------------- |
| Bug fix         | ✔                                                                        |
| New feature     | ✔                                                                        |
| Breaking change | ✖                                                                        |
| Deprecations    | ✖                                                                        |
| Documentation   | ✖                                                                        |
| Tests added     | ✖                                                                        |
| Chore            | ✖                                                                       |

Related issues: #XXX , #XXX ...
Closes #XXX ...

Further  information:

- updated mc-logger
- updated mc-models
- fixed relative openapi support
- added layers controller

2021-01-11 15:44 UTC, asafMasa requested changes

2021-01-11 15:44 UTC, asafMasa commented on src/common/interfaces.ts
> +  log: (level: string, message: string) => void;
why?

2021-01-11 15:44 UTC, asafMasa commented on tests/integration/layers/layers.spec.ts
> +    // it('should return 200 status code and the resource', async function () {
why it is disabled? or commented

2021-01-12 05:52 UTC, cl-shaharshavit-rnd commented on tests/integration/layers/layers.spec.ts
> +    // it('should return 200 status code and the resource', async function () {
I kept is a template for feature test.
there is no logic yet so noting to test

2021-01-12 05:55 UTC, cl-shaharshavit-rnd commented on src/common/interfaces.ts
> +  log: (level: string, message: string) => void;
1) mc-logger 2.0.0 no longer exposes this interface so it cant be used
2) this changes decouples the service from the logger properly, and this decoupling is probably the reason for this interface in the first place

2021-01-12 10:17 UTC, asafMasa approved these changes

2021-01-12 10:19 UTC, merged