fix: files must be stored inside a directory(MAPCO-4562)
MapColonies/discrete-overseer-creator pull request #69
Opened 2024-08-22 06:25 UTC by RonitKissis

| Question                | Answer                                                                          |
| ---------------- | -------------------------------------------------------------------------- |
| Bug fix         | ✔                                                                        |
| New feature     | ✖                                                                        |
| Breaking change | ✖                                                                        |
| Deprecations    | ✖                                                                        |
| Documentation   | ✖                                                                        |
| Tests added     | ✔                                                                        |
| Chore            | ✖                                                                       |

blocks the ability to accept ingestion files that are located straight under the main upload folder in the nfs (due to cleanup service that can delete the entire folder)

2024-08-25 10:45 UTC, CL-SHLOMIKONCHA requested changes

2024-08-25 10:45 UTC, CL-SHLOMIKONCHA commented on src/layers/models/fileValidator.ts
> +      const message = `"originDirectory" cant be right under the nfs main folder`;
```suggestion
      const message = `"originDirectory" value can not be defined as the base directory "/"`;
```

2024-08-25 11:24 UTC, RonitKissis commented on src/layers/models/fileValidator.ts
> +      const message = `"originDirectory" cant be right under the nfs main folder`;
done

2024-08-26 10:06 UTC, CL-SHLOMIKONCHA approved these changes

2024-08-26 10:30 UTC, merged