feat: add sync triggering from overseer
MapColonies/discrete-overseer-creator pull request #76
Opened 2021-09-09 12:04 UTC by asafMasa

Trigger sync process from overseer

| Question                | Answer                                                                          |
| ---------------- | -------------------------------------------------------------------------- |
| New feature     | ✔                                                                        |

2021-09-09 12:06 UTC, asafMasa commented on src/serviceClients/syncClient.ts
> +export class SyncClient extends HttpClient {
Update route

2021-09-13 09:01 UTC, cl-shaharshavit-rnd requested changes

2021-09-13 09:01 UTC, cl-shaharshavit-rnd commented on tests/unit/tasks/models/tasksModel.spec.ts
> +      expect(triggerSyncMock).toHaveBeenCalledTimes(1);
make sure it is also called with the correct value as there is some logic

2021-09-13 10:46 UTC, cl-shaharshavit-rnd approved these changes

2021-09-30 12:56 UTC, merged